language: ruby
dist: xenial
services:
  - postgresql
env:
  matrix:
    - DATABASE_ADAPTER=sqlite3
    - DATABASE_ADAPTER=postgresql
rvm:
  - 2.7.1
  - 2.6.6
  - 2.5.8
  - 2.4.10
gemfile:
  - gemfiles/rails_6_0.gemfile
  - gemfiles/rails_5_2.gemfile
  - gemfiles/rails_5_1.gemfile
  - gemfiles/rails_5_0.gemfile
  - gemfiles/rails_4_2.gemfile
matrix:
  exclude:
    - rvm: 2.7.1
      gemfile: gemfiles/rails_4_2.gemfile
    - rvm: 2.6.6
      gemfile: gemfiles/rails_4_2.gemfile
    - rvm: 2.4.10
      gemfile: gemfiles/rails_6_0.gemfile
cache: bundler
# Source: <https://docs.travis-ci.com/user/languages/ruby/#bundler-20>
before_install:
  - nvm install 12
#  Use Bundler 1.x for Ruby 2.4/2.5 and Rails 4.2
  - |
    if ruby --version | grep -E "2.(4|5)."
    then
      gem update --system '2.7.8' --no-document
      gem uninstall -v '>= 2' -i $(rvm gemdir)@global -ax bundler || true
      gem install bundler -v '< 2' --no-document
    else
      gem update --system --no-document
      gem update bundler --no-document
    fi
install: "bundle install --jobs=3 --retry=3"
script: "bundle exec rake"
